name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm install
        npm link @angular/cli
        npm install -g firebase-tools
        npm run build --prod
      env:
        CI: true
    - name: deploying to Firebase
      run: |
        firebase use "to-do-18eaf" --token ${{ secrets.FIREBASE_TOKEN }}
        firebase deploy --only hosting -m "Pipe $CI_PIPELINE_ID Build $CI_BUILD_ID" --token --token ${{ secrets.FIREBASE_TOKEN }}
